version = "v3.18.0"

[anon-mappings]
"TextDocumentEdit|CreateFile|RenameFile|DeleteFile" = "todo"
"String|Vec<InlayHintLabelPart>" = "todo"
"DiagnosticOptions|DiagnosticRegistrationOptions" = "todo"
"FullDocumentDiagnosticReport|UnchangedDocumentDiagnosticReport" = "todo"
"Location|LocationUriOnly" = "todo"
"MarkupContent|MarkedString|Vec<MarkedString>" = "todo"
"NotebookDocumentFilterWithNotebook|NotebookDocumentFilterWithCells" = "todo"
"NotebookDocumentSyncOptions|NotebookDocumentSyncRegistrationOptions" = "todo"
"Range|EditRangeWithInsertReplace" = "todo"
"SemanticTokensOptions|SemanticTokensRegistrationOptions" = "todo"
"String|(u32,u32)" = "todo"
"String|MarkupContent" = "todo"
"String|NotebookDocumentFilter" = "todo"
"String|StringValue" = "todo"
"String|Vec<String>" = "todo"
"String|bool" = "todo"
"TextDocumentContentOptions|TextDocumentContentRegistrationOptions" = "todo"
"TextDocumentSyncOptions|TextDocumentSyncKind" = "todo"
"TextEdit|AnnotatedTextEdit|SnippetTextEdit" = "todo"
"TextEdit|InsertReplaceEdit" = "todo"
"WorkspaceFolder|Uri" = "todo"
"bool|CallHierarchyOptions|CallHierarchyRegistrationOptions" = "todo"
"bool|ClientSemanticTokensRequestFullDelta" = "todo"
"bool|CodeActionOptions" = "todo"
"bool|DeclarationOptions|DeclarationRegistrationOptions" = "todo"
"bool|DefinitionOptions" = "todo"
"bool|DocumentColorOptions|DocumentColorRegistrationOptions" = "todo"
"bool|DocumentFormattingOptions" = "todo"
"bool|DocumentHighlightOptions" = "todo"
"bool|DocumentRangeFormattingOptions" = "todo"
"bool|DocumentSymbolOptions" = "todo"
"bool|FoldingRangeOptions|FoldingRangeRegistrationOptions" = "todo"
"bool|HoverOptions" = "todo"
"bool|ImplementationOptions|ImplementationRegistrationOptions" = "todo"
"bool|InlayHintOptions|InlayHintRegistrationOptions" = "todo"
"bool|InlineCompletionOptions" = "todo"
"bool|InlineValueOptions|InlineValueRegistrationOptions" = "todo"
"bool|LinkedEditingRangeOptions|LinkedEditingRangeRegistrationOptions" = "todo"
"bool|MonikerOptions|MonikerRegistrationOptions" = "todo"
"bool|ReferenceOptions" = "todo"
"bool|RenameOptions" = "todo"
"bool|SaveOptions" = "todo"
"bool|SelectionRangeOptions|SelectionRangeRegistrationOptions" = "todo"
"bool|SemanticTokensFullDelta" = "todo"
"bool|TypeDefinitionOptions|TypeDefinitionRegistrationOptions" = "todo"
"bool|TypeHierarchyOptions|TypeHierarchyRegistrationOptions" = "todo"
"bool|WorkspaceSymbolOptions" = "todo"
"i64|String" = "todo"

[structs]
WorkDoneProgressBegin = "772515a1"
WorkDoneProgressReport = "3c5e33b1"
WorkDoneProgressEnd = "f29d183a"

AnnotatedTextEdit = true
ApplyWorkspaceEditParams = true
ApplyWorkspaceEditResult = true
BaseSymbolInformation = true
CallHierarchyClientCapabilities = true
CallHierarchyIncomingCall = true
CallHierarchyIncomingCallsParams = true
CallHierarchyItem = true
CallHierarchyOptions = true
CallHierarchyOutgoingCall = true
CallHierarchyOutgoingCallsParams = true
CallHierarchyPrepareParams = true
CallHierarchyRegistrationOptions = true
CancelParams = true
ChangeAnnotation = true
ChangeAnnotationsSupportOptions = true
ClientCapabilities = true
ClientCodeActionKindOptions = true
ClientCodeActionLiteralOptions = true
ClientCodeActionResolveOptions = true
ClientCodeLensResolveOptions = true
ClientCompletionItemInsertTextModeOptions = true
ClientCompletionItemOptions = true
ClientCompletionItemOptionsKind = true
ClientCompletionItemResolveOptions = true
ClientDiagnosticsTagOptions = true
ClientFoldingRangeKindOptions = true
ClientFoldingRangeOptions = true
ClientInfo = true
ClientInlayHintResolveOptions = true
ClientSemanticTokensRequestFullDelta = true
ClientSemanticTokensRequestOptions = true
ClientShowMessageActionItemOptions = true
ClientSignatureInformationOptions = true
ClientSignatureParameterInformationOptions = true
ClientSymbolKindOptions = true
ClientSymbolResolveOptions = true
ClientSymbolTagOptions = true
CodeAction = true
CodeActionClientCapabilities = true
CodeActionContext = true
CodeActionDisabled = true
CodeActionKindDocumentation = true
CodeActionOptions = true
CodeActionParams = true
CodeActionRegistrationOptions = true
CodeActionTagOptions = true
CodeDescription = true
CodeLens = true
CodeLensClientCapabilities = true
CodeLensOptions = true
CodeLensParams = true
CodeLensRegistrationOptions = true
CodeLensWorkspaceClientCapabilities = true
Color = true
ColorInformation = true
ColorPresentation = true
ColorPresentationParams = true
Command = true
CompletionClientCapabilities = true
CompletionContext = true
CompletionItem = true
CompletionItemApplyKinds = true
CompletionItemDefaults = true
CompletionItemLabelDetails = true
CompletionItemTagOptions = true
CompletionList = true
CompletionListCapabilities = true
CompletionOptions = true
CompletionParams = true
CompletionRegistrationOptions = true
ConfigurationItem = true
ConfigurationParams = true
CreateFile = true
CreateFileOptions = true
CreateFilesParams = true
DeclarationClientCapabilities = true
DeclarationOptions = true
DeclarationParams = true
DeclarationRegistrationOptions = true
DefinitionClientCapabilities = true
DefinitionOptions = true
DefinitionParams = true
DefinitionRegistrationOptions = true
DeleteFile = true
DeleteFileOptions = true
DeleteFilesParams = true
Diagnostic = true
DiagnosticClientCapabilities = true
DiagnosticOptions = true
DiagnosticRegistrationOptions = true
DiagnosticRelatedInformation = true
DiagnosticServerCancellationData = true
DiagnosticWorkspaceClientCapabilities = true
DiagnosticsCapabilities = true
DidChangeConfigurationClientCapabilities = true
DidChangeConfigurationParams = true
DidChangeConfigurationRegistrationOptions = true
DidChangeNotebookDocumentParams = true
DidChangeTextDocumentParams = true
DidChangeWatchedFilesClientCapabilities = true
DidChangeWatchedFilesParams = true
DidChangeWatchedFilesRegistrationOptions = true
DidChangeWorkspaceFoldersParams = true
DidCloseNotebookDocumentParams = true
DidCloseTextDocumentParams = true
DidOpenNotebookDocumentParams = true
DidOpenTextDocumentParams = true
DidSaveNotebookDocumentParams = true
DidSaveTextDocumentParams = true
DocumentColorClientCapabilities = true
DocumentColorOptions = true
DocumentColorParams = true
DocumentColorRegistrationOptions = true
DocumentDiagnosticParams = true
DocumentDiagnosticReportPartialResult = true
DocumentFormattingClientCapabilities = true
DocumentFormattingOptions = true
DocumentFormattingParams = true
DocumentFormattingRegistrationOptions = true
DocumentHighlight = true
DocumentHighlightClientCapabilities = true
DocumentHighlightOptions = true
DocumentHighlightParams = true
DocumentHighlightRegistrationOptions = true
DocumentLink = true
DocumentLinkClientCapabilities = true
DocumentLinkOptions = true
DocumentLinkParams = true
DocumentLinkRegistrationOptions = true
DocumentOnTypeFormattingClientCapabilities = true
DocumentOnTypeFormattingOptions = true
DocumentOnTypeFormattingParams = true
DocumentOnTypeFormattingRegistrationOptions = true
DocumentRangeFormattingClientCapabilities = true
DocumentRangeFormattingOptions = true
DocumentRangeFormattingParams = true
DocumentRangeFormattingRegistrationOptions = true
DocumentRangesFormattingParams = true
DocumentSymbol = true
DocumentSymbolClientCapabilities = true
DocumentSymbolOptions = true
DocumentSymbolParams = true
DocumentSymbolRegistrationOptions = true
EditRangeWithInsertReplace = true
ExecuteCommandClientCapabilities = true
ExecuteCommandOptions = true
ExecuteCommandParams = true
ExecuteCommandRegistrationOptions = true
ExecutionSummary = true
FileCreate = true
FileDelete = true
FileEvent = true
FileOperationClientCapabilities = true
FileOperationFilter = true
FileOperationOptions = true
FileOperationPattern = true
FileOperationPatternOptions = true
FileOperationRegistrationOptions = true
FileRename = true
FileSystemWatcher = true
FoldingRange = true
FoldingRangeClientCapabilities = true
FoldingRangeOptions = true
FoldingRangeParams = true
FoldingRangeRegistrationOptions = true
FoldingRangeWorkspaceClientCapabilities = true
FormattingOptions = true
FullDocumentDiagnosticReport = true
GeneralClientCapabilities = true
Hover = true
HoverClientCapabilities = true
HoverOptions = true
HoverParams = true
HoverRegistrationOptions = true
ImplementationClientCapabilities = true
ImplementationOptions = true
ImplementationParams = true
ImplementationRegistrationOptions = true
InitializeError = true
InitializeParams = true
InitializeResult = true
InitializedParams = true
InlayHint = true
InlayHintClientCapabilities = true
InlayHintLabelPart = true
InlayHintOptions = true
InlayHintParams = true
InlayHintRegistrationOptions = true
InlayHintWorkspaceClientCapabilities = true
InlineCompletionClientCapabilities = true
InlineCompletionContext = true
InlineCompletionItem = true
InlineCompletionList = true
InlineCompletionOptions = true
InlineCompletionParams = true
InlineCompletionRegistrationOptions = true
InlineValueClientCapabilities = true
InlineValueContext = true
InlineValueEvaluatableExpression = true
InlineValueOptions = true
InlineValueParams = true
InlineValueRegistrationOptions = true
InlineValueText = true
InlineValueVariableLookup = true
InlineValueWorkspaceClientCapabilities = true
InsertReplaceEdit = true
LinkedEditingRangeClientCapabilities = true
LinkedEditingRangeOptions = true
LinkedEditingRangeParams = true
LinkedEditingRangeRegistrationOptions = true
LinkedEditingRanges = true
Location = true
LocationLink = true
LocationUriOnly = true
LogMessageParams = true
LogTraceParams = true
MarkdownClientCapabilities = true
MarkedStringWithLanguage = true
MarkupContent = true
MessageActionItem = true
Moniker = true
MonikerClientCapabilities = true
MonikerOptions = true
MonikerParams = true
MonikerRegistrationOptions = true
NotebookCell = true
NotebookCellArrayChange = true
NotebookCellLanguage = true
NotebookCellTextDocumentFilter = true
NotebookDocument = true
NotebookDocumentCellChangeStructure = true
NotebookDocumentCellChanges = true
NotebookDocumentCellContentChanges = true
NotebookDocumentChangeEvent = true
NotebookDocumentClientCapabilities = true
NotebookDocumentFilterNotebookType = true
NotebookDocumentFilterPattern = true
NotebookDocumentFilterScheme = true
NotebookDocumentFilterWithCells = true
NotebookDocumentFilterWithNotebook = true
NotebookDocumentIdentifier = true
NotebookDocumentSyncClientCapabilities = true
NotebookDocumentSyncOptions = true
NotebookDocumentSyncRegistrationOptions = true
OptionalVersionedTextDocumentIdentifier = true
ParameterInformation = true
PartialResultParams = true
Position = true
PrepareRenameDefaultBehavior = true
PrepareRenameParams = true
PrepareRenamePlaceholder = true
PreviousResultId = true
ProgressParams = true
PublishDiagnosticsClientCapabilities = true
PublishDiagnosticsParams = true
Range = true
ReferenceClientCapabilities = true
ReferenceContext = true
ReferenceOptions = true
ReferenceParams = true
ReferenceRegistrationOptions = true
Registration = true
RegistrationParams = true
RegularExpressionsClientCapabilities = true
RelatedFullDocumentDiagnosticReport = true
RelatedUnchangedDocumentDiagnosticReport = true
RelativePattern = true
RenameClientCapabilities = true
RenameFile = true
RenameFileOptions = true
RenameFilesParams = true
RenameOptions = true
RenameParams = true
RenameRegistrationOptions = true
ResourceOperation = true
SaveOptions = true
SelectedCompletionInfo = true
SelectionRange = true
SelectionRangeClientCapabilities = true
SelectionRangeOptions = true
SelectionRangeParams = true
SelectionRangeRegistrationOptions = true
SemanticTokens = true
SemanticTokensClientCapabilities = true
SemanticTokensDelta = true
SemanticTokensDeltaParams = true
SemanticTokensDeltaPartialResult = true
SemanticTokensEdit = true
SemanticTokensFullDelta = true
SemanticTokensLegend = true
SemanticTokensOptions = true
SemanticTokensParams = true
SemanticTokensPartialResult = true
SemanticTokensRangeParams = true
SemanticTokensRegistrationOptions = true
SemanticTokensWorkspaceClientCapabilities = true
ServerCapabilities = true
ServerCompletionItemOptions = true
ServerInfo = true
SetTraceParams = true
ShowDocumentClientCapabilities = true
ShowDocumentParams = true
ShowDocumentResult = true
ShowMessageParams = true
ShowMessageRequestClientCapabilities = true
ShowMessageRequestParams = true
SignatureHelp = true
SignatureHelpClientCapabilities = true
SignatureHelpContext = true
SignatureHelpOptions = true
SignatureHelpParams = true
SignatureHelpRegistrationOptions = true
SignatureInformation = true
SnippetTextEdit = true
StaleRequestSupportOptions = true
StaticRegistrationOptions = true
StringValue = true
SymbolInformation = true
TextDocumentChangeRegistrationOptions = true
TextDocumentClientCapabilities = true
TextDocumentContentChangePartial = true
TextDocumentContentChangeWholeDocument = true
TextDocumentContentClientCapabilities = true
TextDocumentContentOptions = true
TextDocumentContentParams = true
TextDocumentContentRefreshParams = true
TextDocumentContentRegistrationOptions = true
TextDocumentContentResult = true
TextDocumentEdit = true
TextDocumentFilterClientCapabilities = true
TextDocumentFilterLanguage = true
TextDocumentFilterPattern = true
TextDocumentFilterScheme = true
TextDocumentIdentifier = true
TextDocumentItem = true
TextDocumentPositionParams = true
TextDocumentRegistrationOptions = true
TextDocumentSaveRegistrationOptions = true
TextDocumentSyncClientCapabilities = true
TextDocumentSyncOptions = true
TextEdit = true
TypeDefinitionClientCapabilities = true
TypeDefinitionOptions = true
TypeDefinitionParams = true
TypeDefinitionRegistrationOptions = true
TypeHierarchyClientCapabilities = true
TypeHierarchyItem = true
TypeHierarchyOptions = true
TypeHierarchyPrepareParams = true
TypeHierarchyRegistrationOptions = true
TypeHierarchySubtypesParams = true
TypeHierarchySupertypesParams = true
UnchangedDocumentDiagnosticReport = true
Unregistration = true
UnregistrationParams = true
VersionedNotebookDocumentIdentifier = true
VersionedTextDocumentIdentifier = true
WillSaveTextDocumentParams = true
WindowClientCapabilities = true
WorkDoneProgressCancelParams = true
WorkDoneProgressCreateParams = true
WorkDoneProgressOptions = true
WorkDoneProgressParams = true
WorkspaceClientCapabilities = true
WorkspaceDiagnosticParams = true
WorkspaceDiagnosticReport = true
WorkspaceDiagnosticReportPartialResult = true
WorkspaceEdit = true
WorkspaceEditClientCapabilities = true
WorkspaceEditMetadata = true
WorkspaceFolder = true
WorkspaceFoldersChangeEvent = true
WorkspaceFoldersInitializeParams = true
WorkspaceFoldersServerCapabilities = true
WorkspaceFullDocumentDiagnosticReport = true
WorkspaceOptions = true
WorkspaceSymbol = true
WorkspaceSymbolClientCapabilities = true
WorkspaceSymbolOptions = true
WorkspaceSymbolParams = true
WorkspaceSymbolRegistrationOptions = true
WorkspaceUnchangedDocumentDiagnosticReport = true
_InitializeParams = true

[enums]
ApplyKind = true
CodeActionKind = true
CodeActionTag = true
CodeActionTriggerKind = true
CompletionItemKind = true
CompletionItemTag = true
CompletionTriggerKind = true
DiagnosticSeverity = true
DiagnosticTag = true
DocumentDiagnosticReportKind = true
DocumentHighlightKind = true
ErrorCodes = true
FailureHandlingKind = true
FileChangeType = true
FileOperationPatternKind = true
FoldingRangeKind = true
InlayHintKind = true
InlineCompletionTriggerKind = true
InsertTextFormat = true
InsertTextMode = true
LanguageKind = true
LSPErrorCodes = true
MarkupKind = true
MessageType = true
MonikerKind = true
NotebookCellKind = true
PositionEncodingKind = true
PrepareSupportDefaultBehavior = true
ResourceOperationKind = true
SemanticTokenModifiers = true
SemanticTokenTypes = true
SignatureHelpTriggerKind = true
SymbolKind = true
SymbolTag = true
TextDocumentSaveReason = true
TextDocumentSyncKind = true
TokenFormat = true
TraceValue = true
UniquenessLevel = true
WatchKind = true
